[package]
name = "nebulax"
version = "0.1.0"
authors = ['nebulax']
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profiles.dev]
debug = 2
lto = true
