complete -c crabup -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c crabup -n "__fish_use_subcommand" -s v -l verbose -d 'Enable verbose output'
complete -c crabup -n "__fish_use_subcommand" -s q -l quiet -d 'Disable progress output'
complete -c crabup -n "__fish_use_subcommand" -f -a "dump-testament" -d 'Dump information about the build'
complete -c crabup -n "__fish_use_subcommand" -f -a "show" -d 'Show the active and installed toolchains or profiles'
complete -c crabup -n "__fish_use_subcommand" -f -a "install" -d 'Update Crab toolchains'
complete -c crabup -n "__fish_use_subcommand" -f -a "uninstall" -d 'Uninstall Crab toolchains'
complete -c crabup -n "__fish_use_subcommand" -f -a "update" -d 'Update Crab toolchains and crabup'
complete -c crabup -n "__fish_use_subcommand" -f -a "check" -d 'Check for updates to Crab toolchains and crabup'
complete -c crabup -n "__fish_use_subcommand" -f -a "default" -d 'Set the default toolchain'
complete -c crabup -n "__fish_use_subcommand" -f -a "toolchain" -d 'Modify or query the installed toolchains'
complete -c crabup -n "__fish_use_subcommand" -f -a "target" -d 'Modify a toolchain\'s supported targets'
complete -c crabup -n "__fish_use_subcommand" -f -a "component" -d 'Modify a toolchain\'s installed components'
complete -c crabup -n "__fish_use_subcommand" -f -a "override" -d 'Modify directory toolchain overrides'
complete -c crabup -n "__fish_use_subcommand" -f -a "run" -d 'Run a command with an environment configured for a given toolchain'
complete -c crabup -n "__fish_use_subcommand" -f -a "which" -d 'Display which binary will be run for a given command'
complete -c crabup -n "__fish_use_subcommand" -f -a "doc" -d 'Open the documentation for the current toolchain'
complete -c crabup -n "__fish_use_subcommand" -f -a "man" -d 'View the man page for a given command'
complete -c crabup -n "__fish_use_subcommand" -f -a "self" -d 'Modify the crabup installation'
complete -c crabup -n "__fish_use_subcommand" -f -a "set" -d 'Alter crabup settings'
complete -c crabup -n "__fish_use_subcommand" -f -a "completions" -d 'Generate tab-completion scripts for your shell'
complete -c crabup -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c crabup -n "__fish_seen_subcommand_from dump-testament" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from show; and not __fish_seen_subcommand_from active-toolchain; and not __fish_seen_subcommand_from home; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from help" -s v -l verbose -d 'Enable verbose output with crabc information for all installed toolchains'
complete -c crabup -n "__fish_seen_subcommand_from show; and not __fish_seen_subcommand_from active-toolchain; and not __fish_seen_subcommand_from home; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from show; and not __fish_seen_subcommand_from active-toolchain; and not __fish_seen_subcommand_from home; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from help" -f -a "active-toolchain" -d 'Show the active toolchain'
complete -c crabup -n "__fish_seen_subcommand_from show; and not __fish_seen_subcommand_from active-toolchain; and not __fish_seen_subcommand_from home; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from help" -f -a "home" -d 'Display the computed value of CRABUP_HOME'
complete -c crabup -n "__fish_seen_subcommand_from show; and not __fish_seen_subcommand_from active-toolchain; and not __fish_seen_subcommand_from home; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from help" -f -a "profile" -d 'Show the current profile'
complete -c crabup -n "__fish_seen_subcommand_from show; and not __fish_seen_subcommand_from active-toolchain; and not __fish_seen_subcommand_from home; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c crabup -n "__fish_seen_subcommand_from show; and __fish_seen_subcommand_from active-toolchain" -s v -l verbose -d 'Enable verbose output with crabc information'
complete -c crabup -n "__fish_seen_subcommand_from show; and __fish_seen_subcommand_from active-toolchain" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from show; and __fish_seen_subcommand_from home" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from show; and __fish_seen_subcommand_from profile" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from install" -l profile -r -f -a "{minimal	,default	,complete	}"
complete -c crabup -n "__fish_seen_subcommand_from install" -l no-self-update -d 'Don\'t perform self-update when running the `crabup install` command'
complete -c crabup -n "__fish_seen_subcommand_from install" -l force -d 'Force an update, even if some components are missing'
complete -c crabup -n "__fish_seen_subcommand_from install" -l force-non-host -d 'Install toolchains that require an emulator. See https://github.com/crab-lang/crabup/wiki/Non-host-toolchains'
complete -c crabup -n "__fish_seen_subcommand_from install" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from uninstall" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from update" -l no-self-update -d 'Don\'t perform self update when running the `crabup update` command'
complete -c crabup -n "__fish_seen_subcommand_from update" -l force -d 'Force an update, even if some components are missing'
complete -c crabup -n "__fish_seen_subcommand_from update" -l force-non-host -d 'Install toolchains that require an emulator. See https://github.com/crab-lang/crabup/wiki/Non-host-toolchains'
complete -c crabup -n "__fish_seen_subcommand_from update" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from check" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from default" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List installed toolchains'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install or update a given toolchain'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from help" -f -a "uninstall" -d 'Uninstall a toolchain'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from help" -f -a "link" -d 'Create a custom toolchain by symlinking to a directory'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from link; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from list" -s v -l verbose -d 'Enable verbose output with toolchain information'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from install" -l profile -r -f -a "{minimal	,default	,complete	}"
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from install" -s c -l component -d 'Add specific components on installation' -r
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from install" -s t -l target -d 'Add specific targets on installation' -r
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from install" -l no-self-update -d 'Don\'t perform self update when running the`crabup toolchain install` command'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from install" -l force -d 'Force an update, even if some components are missing'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from install" -l allow-downgrade -d 'Allow crabup to downgrade the toolchain to satisfy your component choice'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from install" -l force-non-host -d 'Install toolchains that require an emulator. See https://github.com/crab-lang/crabup/wiki/Non-host-toolchains'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from install" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from uninstall" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from toolchain; and __fish_seen_subcommand_from link" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from target; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from target; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List installed and available targets'
complete -c crabup -n "__fish_seen_subcommand_from target; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "add" -d 'Add a target to a Crab toolchain'
complete -c crabup -n "__fish_seen_subcommand_from target; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove a target from a Crab toolchain'
complete -c crabup -n "__fish_seen_subcommand_from target; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c crabup -n "__fish_seen_subcommand_from target; and __fish_seen_subcommand_from list" -l toolchain -d 'Toolchain name, such as \'stable\', \'nightly\', or \'1.8.0\'. For more information see `crabup help toolchain`' -r
complete -c crabup -n "__fish_seen_subcommand_from target; and __fish_seen_subcommand_from list" -l installed -d 'List only installed targets'
complete -c crabup -n "__fish_seen_subcommand_from target; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from target; and __fish_seen_subcommand_from add" -l toolchain -d 'Toolchain name, such as \'stable\', \'nightly\', or \'1.8.0\'. For more information see `crabup help toolchain`' -r
complete -c crabup -n "__fish_seen_subcommand_from target; and __fish_seen_subcommand_from add" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from target; and __fish_seen_subcommand_from remove" -l toolchain -d 'Toolchain name, such as \'stable\', \'nightly\', or \'1.8.0\'. For more information see `crabup help toolchain`' -r
complete -c crabup -n "__fish_seen_subcommand_from target; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from component; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from component; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List installed and available components'
complete -c crabup -n "__fish_seen_subcommand_from component; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "add" -d 'Add a component to a Crab toolchain'
complete -c crabup -n "__fish_seen_subcommand_from component; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove a component from a Crab toolchain'
complete -c crabup -n "__fish_seen_subcommand_from component; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c crabup -n "__fish_seen_subcommand_from component; and __fish_seen_subcommand_from list" -l toolchain -d 'Toolchain name, such as \'stable\', \'nightly\', or \'1.8.0\'. For more information see `crabup help toolchain`' -r
complete -c crabup -n "__fish_seen_subcommand_from component; and __fish_seen_subcommand_from list" -l installed -d 'List only installed components'
complete -c crabup -n "__fish_seen_subcommand_from component; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from component; and __fish_seen_subcommand_from add" -l toolchain -d 'Toolchain name, such as \'stable\', \'nightly\', or \'1.8.0\'. For more information see `crabup help toolchain`' -r
complete -c crabup -n "__fish_seen_subcommand_from component; and __fish_seen_subcommand_from add" -l target -r
complete -c crabup -n "__fish_seen_subcommand_from component; and __fish_seen_subcommand_from add" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from component; and __fish_seen_subcommand_from remove" -l toolchain -d 'Toolchain name, such as \'stable\', \'nightly\', or \'1.8.0\'. For more information see `crabup help toolchain`' -r
complete -c crabup -n "__fish_seen_subcommand_from component; and __fish_seen_subcommand_from remove" -l target -r
complete -c crabup -n "__fish_seen_subcommand_from component; and __fish_seen_subcommand_from remove" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from override; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from unset; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from override; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from unset; and not __fish_seen_subcommand_from help" -f -a "list" -d 'List directory toolchain overrides'
complete -c crabup -n "__fish_seen_subcommand_from override; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from unset; and not __fish_seen_subcommand_from help" -f -a "set" -d 'Set the override toolchain for a directory'
complete -c crabup -n "__fish_seen_subcommand_from override; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from unset; and not __fish_seen_subcommand_from help" -f -a "unset" -d 'Remove the override toolchain for a directory'
complete -c crabup -n "__fish_seen_subcommand_from override; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from set; and not __fish_seen_subcommand_from unset; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c crabup -n "__fish_seen_subcommand_from override; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from override; and __fish_seen_subcommand_from set" -l path -d 'Path to the directory' -r
complete -c crabup -n "__fish_seen_subcommand_from override; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from override; and __fish_seen_subcommand_from unset" -l path -d 'Path to the directory' -r
complete -c crabup -n "__fish_seen_subcommand_from override; and __fish_seen_subcommand_from unset" -l nonexistent -d 'Remove override toolchain for all nonexistent directories'
complete -c crabup -n "__fish_seen_subcommand_from override; and __fish_seen_subcommand_from unset" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from run" -l install -d 'Install the requested toolchain if needed'
complete -c crabup -n "__fish_seen_subcommand_from run" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from which" -l toolchain -d 'Toolchain name, such as \'stable\', \'nightly\', or \'1.8.0\'. For more information see `crabup help toolchain`' -r
complete -c crabup -n "__fish_seen_subcommand_from which" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l toolchain -d 'Toolchain name, such as \'stable\', \'nightly\', or \'1.8.0\'. For more information see `crabup help toolchain`' -r
complete -c crabup -n "__fish_seen_subcommand_from doc" -l path -d 'Only print the path to the documentation'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l alloc -d 'The Crab core allocation and collections library'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l book -d 'The Crab Programming Language book'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l crabgo -d 'The Crabgo Book'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l core -d 'The Crab Core Library'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l edition-guide -d 'The Crab Edition Guide'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l nomicon -d 'The Dark Arts of Advanced and Unsafe Crab Programming'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l proc_macro -d 'A support library for macro authors when defining new macros'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l reference -d 'The Crab Reference'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l crab-by-example -d 'A collection of runnable examples that illustrate various Crab concepts and standard libraries'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l crabc -d 'The compiler for the Crab programming language'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l crabdoc -d 'Documentation generator for Crab projects'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l std -d 'Standard library API documentation'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l test -d 'Support code for crabc\'s built in unit-test and micro-benchmarking framework'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l unstable-book -d 'The Unstable Book'
complete -c crabup -n "__fish_seen_subcommand_from doc" -l embedded-book -d 'The Embedded Crab Book'
complete -c crabup -n "__fish_seen_subcommand_from doc" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from man" -l toolchain -d 'Toolchain name, such as \'stable\', \'nightly\', or \'1.8.0\'. For more information see `crabup help toolchain`' -r
complete -c crabup -n "__fish_seen_subcommand_from man" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from self; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from upgrade-data; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from self; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from upgrade-data; and not __fish_seen_subcommand_from help" -f -a "update" -d 'Download and install updates to crabup'
complete -c crabup -n "__fish_seen_subcommand_from self; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from upgrade-data; and not __fish_seen_subcommand_from help" -f -a "uninstall" -d 'Uninstall crabup.'
complete -c crabup -n "__fish_seen_subcommand_from self; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from upgrade-data; and not __fish_seen_subcommand_from help" -f -a "upgrade-data" -d 'Upgrade the internal data format.'
complete -c crabup -n "__fish_seen_subcommand_from self; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from uninstall; and not __fish_seen_subcommand_from upgrade-data; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c crabup -n "__fish_seen_subcommand_from self; and __fish_seen_subcommand_from update" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from self; and __fish_seen_subcommand_from uninstall" -s y
complete -c crabup -n "__fish_seen_subcommand_from self; and __fish_seen_subcommand_from uninstall" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from self; and __fish_seen_subcommand_from upgrade-data" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from default-host; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from auto-self-update; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from default-host; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from auto-self-update; and not __fish_seen_subcommand_from help" -f -a "default-host" -d 'The triple used to identify toolchains when not specified'
complete -c crabup -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from default-host; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from auto-self-update; and not __fish_seen_subcommand_from help" -f -a "profile" -d 'The default components installed'
complete -c crabup -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from default-host; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from auto-self-update; and not __fish_seen_subcommand_from help" -f -a "auto-self-update" -d 'The crabup auto self update mode'
complete -c crabup -n "__fish_seen_subcommand_from set; and not __fish_seen_subcommand_from default-host; and not __fish_seen_subcommand_from profile; and not __fish_seen_subcommand_from auto-self-update; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c crabup -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from default-host" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from profile" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from set; and __fish_seen_subcommand_from auto-self-update" -s h -l help -d 'Print help information'
complete -c crabup -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Print help information'
