local opt = vim.opt

--opt.clipboard = 'unnamed'
opt.autoindent = true
opt.background = "dark"
opt.backspace = "indent,eol,start"
opt.backup = false
opt.breakindent = true
opt.clipboard = 'unnamedplus'
opt.completeopt = { 'menu', 'menuone', 'preview', 'noinsert', 'noselect' }
opt.cursorcolumn = false
opt.cursorline = true
opt.expandtab = true
opt.fillchars = { eob = " ", lastline = " " }
opt.foldenable = false
opt.guicursor = { a = "Block" }
opt.hlsearch = false
opt.icon = true
opt.inccommand = 'split'
opt.incsearch = true
opt.isfname = { '@-@' }
opt.list = false
opt.number = true
opt.pumblend = 15
opt.redrawtime = 500
opt.relativenumber = true
opt.scroll = 10
opt.scrollback = 10
opt.scrolloff = 12
opt.shiftwidth = 4
opt.shortmess = "aI"
opt.showmatch = false
opt.sidescrolloff = 100
opt.signcolumn = 'yes'
opt.smartindent = true
opt.softtabstop = 4
opt.splitbelow = false
opt.splitright = true
opt.swapfile = false
opt.tabstop = 4
opt.termguicolors = true
opt.undodir = os.getenv("HOME") .. "/.config/nvim/undodir"
opt.undofile = true
opt.updatetime = 50
opt.wildignore = { "Cargo.lock" }
opt.wrap = false
